# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16YxUcoegvUXuFWtB0AflZLLV7KTiGiYp
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
data=pd.read_excel("/content/drive/MyDrive/Colab Notebooks/ott-theatre 1.xlsx")
print("Mean = ",data.OTT_USERS.mean())
print("Median = ",data.OTT_USERS.median())
print("Mode = ",data.OTT_USERS.mode())
print("Std.Deviation = ",data.OTT_USERS.std())
print("Variance = ",data.OTT_USERS.var())

print("Mean = ",data.THEATRE_USERS.mean())
print("Median = ",data.THEATRE_USERS.median())
print("Mode = ",data.THEATRE_USERS.mode())
print("Std.Deviation = ",data.THEATRE_USERS.std())
print("Variance = ",data.THEATRE_USERS.var())


if(data.OTT_USERS.mean()>data.THEATRE_USERS.mean()):
    print("OTT is preffered")
else:
    print("THEATRE is preffered")